// campusData3D.js — JNTU Vizianagaram 3D Building Definitions
// Each building maps to your existing 2D map buildings.
// Positions are in local 3D space (Three.js units ≈ meters).
// Adjust x/z to match real campus layout.

export const CAMPUS_BUILDINGS_3D = [

  // ── BOYS HOSTELS ──────────────────────────────────────────────────
  {
    id: 'HOSTEL_BOYS_1',
    name: 'Boys Hostel I',
    shortName: 'BH-1',
    type: 'Boys Hostel',
    icon: '🏠',
    width: 16, height: 9.6, depth: 10,   // 3 floors
    x: -22, z: 14,
    dayColor:   0xd4cfc8,
    nightColor: 0x1a2a4a,
    floors: 3,
    capacity: 240,
    established: 2005,
    description: 'Boys Hostel I houses 240 male students with modern amenities including a common room, study hall, and sports facilities.',
    tags: ['Residential', 'Boys', '3 Floors', 'Sports Court'],
    badgeColor: '#1d4ed8',
    link: '/map?select=HOSTEL_BOYS_1',
  },
  {
    id: 'HOSTEL_BOYS_2',
    name: 'Boys Hostel II',
    shortName: 'BH-2',
    type: 'Boys Hostel',
    icon: '🏠',
    width: 18, height: 12.8, depth: 11,   // 4 floors
    x: -30, z: 8,
    dayColor:   0xcecac2,
    nightColor: 0x162238,
    floors: 4,
    capacity: 320,
    established: 2010,
    description: 'Boys Hostel II is the larger residential facility providing 320 rooms with a warden office, laundry, and 24-hour security.',
    tags: ['Residential', 'Boys', '4 Floors', 'Laundry', 'Security'],
    badgeColor: '#1d4ed8',
    link: '/map?select=HOSTEL_BOYS_2',
  },

  // ── GIRLS HOSTELS ─────────────────────────────────────────────────
  {
    id: 'HOSTEL_GIRLS_1',
    name: 'Girls Hostel I',
    shortName: 'GH-1',
    type: 'Girls Hostel',
    icon: '🏠',
    width: 15, height: 9.6, depth: 10,
    x: 28, z: 14,
    dayColor:   0xe8d5d0,
    nightColor: 0x2a1a2a,
    floors: 3,
    capacity: 210,
    established: 2006,
    description: 'Girls Hostel I is a fully secured residential block for female students with warden accommodation and CCTV surveillance.',
    tags: ['Residential', 'Girls', '3 Floors', 'CCTV', 'Secured'],
    badgeColor: '#9d174d',
    link: '/map?select=HOSTEL_GIRLS_1',
  },
  {
    id: 'HOSTEL_GIRLS_2',
    name: 'Girls Hostel II',
    shortName: 'GH-2',
    type: 'Girls Hostel',
    icon: '🏠',
    width: 16, height: 12.8, depth: 10,
    x: 28, z: 25,
    dayColor:   0xddc8c4,
    nightColor: 0x221526,
    floors: 4,
    capacity: 280,
    established: 2012,
    description: 'Girls Hostel II is the newer residential block with enhanced facilities, indoor recreation room, and study lounge.',
    tags: ['Residential', 'Girls', '4 Floors', 'Recreation', 'Study Lounge'],
    badgeColor: '#9d174d',
    link: '/map?select=HOSTEL_GIRLS_2',
  },

  // ── LIBRARY ───────────────────────────────────────────────────────
  {
    id: 'LIBRARY',
    name: 'YSR Central Library',
    shortName: 'Library',
    type: 'Academic Library',
    icon: '📚',
    width: 22, height: 12, depth: 16,
    x: 6, z: 0,
    dayColor:   0xc8b89a,
    nightColor: 0x12203a,
    floors: 3,
    capacity: 500,
    established: 2000,
    description: 'The YSR Central Library is the knowledge hub of JNTU Vizianagaram, housing over 50,000 volumes, digital research terminals, and quiet reading zones.',
    tags: ['Library', '50K+ Books', 'Digital Access', 'Reading Zones'],
    badgeColor: '#92400e',
    link: '/library',
  },

  // ── ACADEMIC BLOCKS ───────────────────────────────────────────────
  {
    id: 'BLOCK_BS',
    name: 'B.S. & H. Block',
    shortName: 'BS&H',
    type: 'Academic Block',
    icon: '🏫',
    width: 20, height: 12.8, depth: 12,
    x: -8, z: -22,
    dayColor:   0xbeb8b0,
    nightColor: 0x101a30,
    floors: 4,
    capacity: 800,
    established: 1998,
    description: 'The Basic Sciences and Humanities block houses Chemistry, Physics, Mathematics, and English language departments with well-equipped labs.',
    tags: ['Sciences', 'Humanities', 'Labs', '4 Floors'],
    badgeColor: '#065f46',
    link: '/map?select=BLOCK_BS',
  },
  {
    id: 'BLOCK_MW',
    name: 'Mechanical Workshop',
    shortName: 'MW',
    type: 'Workshop',
    icon: '⚙️',
    width: 24, height: 6, depth: 18,    // Single storey, wide
    x: 10, z: -26,
    dayColor:   0xa8a49c,
    nightColor: 0x0e1828,
    windows: false,
    floors: 1,
    capacity: 200,
    established: 2001,
    description: 'The Mechanical Workshop features CNC machines, welding stations, lathe machines, and a fabrication area for engineering practicals.',
    tags: ['Workshop', 'CNC', 'Welding', 'Fabrication'],
    badgeColor: '#78350f',
    link: '/map?select=BLOCK_MW',
  },
  {
    id: 'BLOCK_CSE',
    name: 'CSE / IT Block',
    shortName: 'CSE/IT',
    type: 'Academic Block',
    icon: '💻',
    width: 18, height: 16, depth: 12,   // 5 floors — tallest academic
    x: -18, z: -32,
    dayColor:   0xc4ccd8,
    nightColor: 0x0d1a30,
    floors: 5,
    capacity: 1200,
    established: 2003,
    description: 'The CSE & IT block is the tallest academic building, hosting high-speed computer labs, AI research lab, and the department offices.',
    tags: ['CSE', 'IT', '5 Floors', 'AI Lab', 'High-Speed Internet'],
    badgeColor: '#1e3a5f',
    link: '/map?select=BLOCK_CSE',
  },

  // ── ADMIN BLOCK ───────────────────────────────────────────────────
  {
    id: 'ADMIN',
    name: 'Administrative Block',
    shortName: 'Admin',
    type: 'Administration',
    icon: '🏛️',
    width: 20, height: 12.8, depth: 14,
    x: 0, z: -38,
    dayColor:   0xd8d0c4,
    nightColor: 0x14202e,
    floors: 4,
    capacity: 150,
    established: 1997,
    description: 'The Administrative Block is the main governance hub of the university, housing the Registrar, Principal office, examination cell, and finance department.',
    tags: ['Administration', 'Principal Office', 'Examinations', 'Finance'],
    badgeColor: '#374151',
    link: '/map?select=ADMIN',
  },

  // ── CANTEEN ───────────────────────────────────────────────────────
  {
    id: 'CANTEEN',
    name: 'Main Canteen',
    shortName: 'Canteen',
    type: 'Food & Beverage',
    icon: '🍔',
    width: 16, height: 4, depth: 12,
    x: 22, z: -18,
    dayColor:   0xd4aa70,
    nightColor: 0x1a1208,
    windows: false,
    entrance: true,
    floors: 1,
    capacity: 300,
    established: 2005,
    description: 'The Main Canteen serves breakfast, lunch, and dinner for students and faculty with a dedicated vegetarian section and juice bar.',
    tags: ['Food', 'Vegetarian', 'Juice Bar', 'Open 7am-10pm'],
    badgeColor: '#92400e',
    link: '/map?select=CANTEEN',
  },

  // ── ESTATE OFFICE ─────────────────────────────────────────────────
  {
    id: 'ESTATE',
    name: 'Estate Office',
    shortName: 'Estate',
    type: 'Administration',
    icon: '🏗️',
    width: 10, height: 6.4, depth: 8,
    x: 38, z: -28,
    dayColor:   0xc0b8a8,
    nightColor: 0x121820,
    floors: 2,
    capacity: 30,
    established: 2000,
    description: 'The Estate Office manages campus infrastructure, maintenance, electrical systems, and construction activities across the university.',
    tags: ['Infrastructure', 'Maintenance', 'Construction'],
    badgeColor: '#374151',
    link: '/map?select=ESTATE',
  },

  // ── MEDICAL CENTRE ────────────────────────────────────────────────
  {
    id: 'MEDICAL',
    name: 'Medical Centre',
    shortName: 'Medical',
    type: 'Medical',
    icon: '💊',
    width: 10, height: 6.4, depth: 8,
    x: -40, z: -15,
    dayColor:   0xe8f0e8,
    nightColor: 0x0e1e12,
    floors: 2,
    capacity: 50,
    established: 2001,
    description: 'The campus Medical Centre provides first aid, outpatient consultation, and a dispensary for students and staff.',
    tags: ['Medical', 'First Aid', 'Dispensary', '24/7 Emergency'],
    badgeColor: '#065f46',
    link: '/map?select=MEDICAL',
  },
];